language: rust
sudo: false
rust:
- stable
- beta
matrix:
    include:
    - rust: nightly
      script:
      - cargo test --verbose
      - cargo test --no-default-features --verbose
      - cargo test --features serde-1
      after_script: cargo bench --verbose
